### ISSUE TITLE
cargo build fails on macOS 11.4 on M1

### ISSUE THREAD

**Issue by stijn-uva** [quickwit-inc/tantivy#1320]
**Describe the bug**
When checking out Tantivy (latest or the 0.17 tag) and building it on macOS Big Sur (11.4), it fails with the following error(s):

```
   Compiling tantivy v0.17.0 (/opt/tantivy-0.17)
error: there is no argument named `field_name`
   --> src/core/segment_reader.rs:124:49
    |
124 |                 "Field norm not found for field {field_name:?}. Was the field set to record norm \
    |                                                 ^^^^^^^^^^^^^^

error: there is no argument named `per_thread_memory_budget`
  --> src/indexer/segment_writer.rs:32:45
   |
32 |                 "per thread memory budget (={per_thread_memory_budget}) is too small. Raise the \
   |                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^

error: there is no argument named `phrase`
   --> src/query/query_parser/query_parser.rs:357:76
    |
357 |                         "Range query boundary cannot have multiple tokens: {phrase:?}."
    |                                                                            ^^^^^^^^^^

error: there is no argument named `path_pretty`
   --> src/schema/term.rs:393:33
    |
393 |                 write!(f, "path={path_pretty}, vtype={typ:?}, ")?;
    |                                 ^^^^^^^^^^^^^

error: there is no argument named `typ`
   --> src/schema/term.rs:393:54
    |
393 |                 write!(f, "path={path_pretty}, vtype={typ:?}, ")?;
    |                                                      ^^^^^^^

error: there is no argument named `typ`
   --> src/schema/term.rs:407:30
    |
407 |         write!(f, "Term(type={typ:?}, field={field_id}, ")?;
    |                              ^^^^^^^

error: there is no argument named `field_id`
   --> src/schema/term.rs:407:45
    |
407 |         write!(f, "Term(type={typ:?}, field={field_id}, ")?;
    |                                             ^^^^^^^^^^

error[E0658]: use of unstable library feature 'array_methods'
   --> src/indexer/json_term_writer.rs:259:59
    |
259 |             .extend_from_slice(val.to_u64().to_be_bytes().as_slice());
    |                                                           ^^^^^^^^
    |
    = note: see issue #76118 <https://github.com/rust-lang/rust/issues/76118> for more information

error: aborting due to 8 previous errors
```

**Which version of tantivy are you using?**
Tag 0.17, or master as of 125707dbe01e826acd77b826ff9378839cb95214. Rust 1.59.0 [via Homebrew](https://formulae.brew.sh/formula/rust#default), cargo 1.54.0.

**To Reproduce**
Following the build instructions in the readme with the software versions described above reproduces this consistently. I lack an Intel Mac, however, so I can't be sure if this is reproducible e.g. only on M1 Macs or if it is a wider problem.

**Comment by fulmicoton** [comment]
@fmassot can you reproduce on your mac?

**Comment by fmassot** [comment]
@stijn-uva thanks for the report.

It's working fine on my M1 with cargo 1.59.0 and rustc 1.59.0.

Can you try after a cargo upgrade?

**Comment by stijn-uva** [comment]
Looks like after forcing Homebrew to upgrade from 1.54.0 to 1.59.0 it works. I wonder why it wasn't in sync with the rustc version in the first place. That's a bit embarassing, sorry for wasting your time!
